config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "staff_constraint"
require "googleauth"

Rails.application.routes.draw do
  mount Peek::Railtie => "/peek"
  mount ActionCable.server => "/cable"

  root to: "pages#home"

  get "/assistant", to: "pages#assistant"
  get "/help/(:article_name)", to: "pages#help", as: "help"
  get "/home", to: "pages#home"

  get  "/login",  to: "sessions#new",     as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"

  get  "/login/oauth/authorize", to: "oauth#authorize"
  post "/login/oauth/access_token", to: "oauth#access_token"

  post "/auth/lti/launch",          to: "sessions#lti_launch"
  get "/auth/lti/setup",            to: "sessions#lti_setup"
  get "/auth/lti/failure",          to: "sessions#lti_failure"
  match "/auth/:provider/callback", to: "sessions#create",        via: %i[get post]
  match "/auth/failure",            to: "sessions#failure",       via: %i[get post]

  match "/google_classroom/oauth2_callback", to: Google::Auth::WebUserAuthorizer::CallbackApp, via: :all

  get "/a/:short_key", to: "short_url#assignment_invitation",       as: "assignment_invitation_short"
  get "/g/:short_key", to: "short_url#group_assignment_invitation", as: "group_assignment_invitation_short"

  get "/autocomplete/github_repos", to: "autocomplete#github_repos"

  get "/boom", to: "site#boom_town"
  get "/boom/sidekiq", to: "site#boom_sidekiq"

  scope "github", as: "github" do
    constraints user_agent: %r{\AGitHub-Hookshot/\w+\z}, format: "json" do
      post :hooks, to: "hooks#receive"
    end
  end

  resources :assignment_invitations, path: "assignment-invitations", only: [:show] do
    member do
      patch :accept
      get   :setup
      post  :create_repo
      get   :progress
      get   :success
      patch :join_roster
    end
  end

  resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :setup
      post  :create_repo
      get   :progress
      get   :successful_invitation, path: :success
      patch :join_roster
    end
  end

  scope path_names: { edit: "settings" } do
    resources :organizations, path: "classrooms" do
      collection do
        get :search
      end

      member do
        get   :link_lms
        get   :invite
        get   :new_assignment, path: "new-assignment"
        get   :setup
        patch :setup_organization
        get   "settings/invitations", to: "organizations#invitation"
        get   "settings/teams",       to: "organizations#show_groupings"
        delete "users/:user_id",      to: "organizations#remove_user", as: "remove_user"

        resource :roster, only: %i[show new create], controller: "orgs/rosters" do
          patch :link
          patch :unlink
          patch :delete_entry
          patch :edit_entry
          patch :add_students
          patch :remove_organization
          patch :import_from_google_classroom
          patch :sync_google_classroom
          get   :import_from_lms
        end

        resource :lti_configuration, controller: "orgs/lti_configurations" do
          get :info
          get :autoconfigure
          get :complete
        end

        scope :google_classrooms do
          root "orgs/google_classroom_configurations#index", as: :google_classrooms_index
          get  "search", to: "orgs/google_classroom_configurations#search", as: "google_classrooms_search"
          post "create", to: "orgs/google_classroom_configurations#create", as: "google_classrooms_create"
          delete "delete", to: "orgs/google_classroom_configurations#destroy", as: "google_classrooms_delete"
        end
      end

      resources :groupings, only: %i[show edit update] do
        resources :groups, only: [:show] do
          member do
            patch "/memberships/:user_id", to: "groups#add_membership", as: "add_membership"
            delete "/memberships/:user_id", to: "groups#remove_membership", as: "remove_membership"
          end
        end
      end

      resources :assignments do
        resources :assignment_repos, only: [:show], controller: "orgs/assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
        get :assistant, on: :member
        member do
          post :toggle_invitations
        end
      end

      resources :group_assignments, path: "group-assignments" do
        resources :group_assignment_repos, only: [:show], controller: "orgs/group_assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
        get :assistant, on: :member
        member do
          post :toggle_invitations
        end
      end
    end
  end

  resources :videos, only: [:index]

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => "/sidekiq"
      mount Flipper::UI.app(GitHubClassroom.flipper) => "/flipper", as: "flipper"
    end

    root "resources#index", as: :root
    get "/resource_search", to: "resources#search"

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: "classrooms", only: [:show] do
      member do
        delete "/users/:user_id", to: "organizations#remove_user", as: "remove_user"
        post :ensure_webhook_is_active
      end
    end

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: %i[show destroy]
    resources :assignments,            only: [:show]

    resources :deadlines, only: [:show]

    resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show]
    resources :group_assignment_repos,       path: "group-assignment-repos",       only: %i[show destroy]
    resources :group_assignments,            path: "group-assignments",            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end

  namespace :api, defaults: { format: :json } do
    scope :internal do
      scope "classrooms/:organization_id" do
        resources :assignments, only: %i[index show] do
          resources :assignment_repos, only: [:index] do
            get "/clone_url", to: "assignment_repos#clone_url"
          end
        end
        resources :group_assignments, path: "group-assignments", only: %i[index show] do
          resources :group_assignment_repos, path: "group-assignment-repos", only: [:index] do
            get "/clone_url", to: "group_assignment_repos#clone_url"
          end
        end
      end
      get "/user", to: "users#authenticated_user"
    end
  end
end

app/models/roster.rb
# frozen_string_literal: true

class Roster < ApplicationRecord
  has_many :roster_entries, dependent: :destroy
  has_many :organizations

  validates :identifier_name, presence: true
  validates :roster_entries, presence: true

  include DuplicateRosterEntries

  def unlinked_entries
    roster_entries.includes(:user).select do |entry|
      entry.user.nil?
    end
  end
end

app/controllers/orgs/assignment_repos_controller.rb
# frozen_string_literal: true

module Orgs
  class AssignmentReposController < Orgs::Controller
    layout false

    def show
      @assignment_repo = AssignmentRepo.includes(:user).find_by!(id: params[:id], assignment: current_assignment)
    end

    private

    def current_assignment
      return @current_assignment if defined?(@current_assignment)
      @current_assignment = current_organization.assignments.find_by(slug: params[:assignment_id])
    end
  end
end

app/controllers/orgs/controller.rb
# frozen_string_literal: true

module Orgs
  class Controller < ApplicationController
    before_action :ensure_current_organization
    before_action :ensure_current_organization_visible_to_current_user

    protected

    def add_current_user_to_current_organization_or_404
      github_organization = GitHubOrganization.new(current_user.github_client, current_organization.github_id)
      return not_found unless github_organization.admin?(current_user.github_user.login)
      current_organization.users << current_user
      true
    end

    def ensure_current_organization
      not_found if current_organization.nil?
    end

    def ensure_current_organization_visible_to_current_user
      return true if current_organization.users.pluck(:id).include?(current_user.id)
      add_current_user_to_current_organization_or_404
    end

    def current_organization
      return @current_organization if defined?(@current_organization)
      organization_id = params[:organization_id] || params[:id]
      @current_organization = Organization.find_by!(slug: organization_id)
    end
    helper_method :current_organization

    def failbot_context
      super unless current_organization.nil?
      super.merge(organization: current_organization.id)
    end
  end
end

app/controllers/orgs/google_classroom_configurations_controller.rb
# frozen_string_literal: true

require "google/apis/classroom_v1"

module Orgs
  class GoogleClassroomConfigurationsController < Orgs::Controller
    before_action :ensure_google_classroom_roster_import_is_enabled, only: %i[create search index]
    before_action :authorize_google_classroom, only: %i[create search index]
    before_action :ensure_no_lti_configuration, only: %i[create index]
    before_action :ensure_no_roster, only: %i[create index]

    def create
      current_organization.update(google_course_id: params[:course_id])

      GitHubClassroom.statsd.increment("google_classroom.create")

      flash[:success] = "Google Classroom integration was succesfully configured."
      redirect_to new_roster_path(current_organization)
    end

    def search
      courses_found = fetch_all_google_classrooms.select do |course|
        course.name.downcase.include? params[:query].downcase
      end

      respond_to do |format|
        format.html do
          render partial: "google_classroom_collection",
                 locals: { courses: courses_found }
        end
      end
    end

    def index
      @google_classroom_courses = fetch_all_google_classrooms
    rescue Google::Apis::AuthorizationError, Signet::AuthorizationError
      google_classroom_client = GitHubClassroom.google_classroom_client
      login_hint = current_user.github_user.login
      redirect_to google_classroom_client.get_authorization_url(login_hint: login_hint, request: request)
    rescue Google::Apis::ServerError, Google::Apis::ClientError
      flash[:error] = "Failed to fetch classroom from Google Classroom. Please try again."
      redirect_to organization_path(current_organization)
    end

    def destroy
      current_organization.update!(google_course_id: nil)
      GitHubClassroom.statsd.increment("google_classroom.destroy")
      flash[:success] = "Removed link to Google Classroom. No students were removed from your roster."

      redirect_to organization_path(current_organization)
    end

    private

    def ensure_no_lti_configuration
      return unless current_organization.lti_configuration
      lms_name = current_organization.lti_configuration.lms_name(default_name: "a learning management system")
      redirect_to edit_organization_path(current_organization),
        alert: "This classroom is already connected to #{lms_name}. Please disconnect from #{lms_name} before "\
        "connecting to Google Classroom."
    end

    def ensure_no_roster
      return unless current_organization.roster
      redirect_to edit_organization_path(current_organization),
        alert: "We are unable to link your classroom organization to Google Classroom "\
          "because a roster already exists. Please delete your current roster and try again."
    end

    def fetch_all_google_classrooms
      next_page = nil
      courses = []
      loop do
        response = @google_classroom_service.list_courses(course_states: "ACTIVE", page_size: 20, page_token: next_page)

        courses.push(*response.courses)

        next_page = response.next_page_token
        break unless next_page
      end

      courses
    end
  end
end

app/controllers/orgs/group_assignment_repos_controller.rb
# frozen_string_literal: true

module Orgs
  class GroupAssignmentReposController < Orgs::Controller
    layout false

    def show
      @group_assignment_repo = GroupAssignmentRepo.includes(:group).find_by!(
        id: params[:id],
        group_assignment: current_group_assignment
      )
    end

    private

    def current_group_assignment
      return @current_assignment if defined?(@current_assignment)
      @current_assignment = current_organization.group_assignments.find_by(slug: params[:group_assignment_id])
    end
  end
end

app/controllers/orgs/lti_configurations_controller.rb
# frozen_string_literal: true

module Orgs
  class LtiConfigurationsController < Orgs::Controller
    before_action :ensure_lti_launch_flipper_is_enabled
    before_action :ensure_current_lti_configuration, except: %i[info new create]
    before_action :ensure_no_google_classroom, only: %i[new create]
    before_action :ensure_no_roster, only: %i[new create]
    before_action :ensure_lms_type, only: %i[create]

    skip_before_action :authenticate_user!, only: :autoconfigure
    skip_before_action :ensure_lti_launch_flipper_is_enabled, only: :autoconfigure
    skip_before_action :ensure_current_organization_visible_to_current_user, only: :autoconfigure

    # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
    def create
      lti_configuration = LtiConfiguration.create(
        organization: current_organization,
        lms_type: lti_configuration_params[:lms_type],
        consumer_key: SecureRandom.uuid,
        shared_secret: SecureRandom.uuid
      )

      if lti_configuration.present?
        GitHubClassroom.statsd.increment("lti_configuration.create")
        redirect_to lti_configuration_path(current_organization)
      else
        redirect_to info_lti_configuration_path(current_lti_configuration),
          alert: "There was a problem creating the configuration. Please try again later."
      end
    end
    # rubocop:enable Metrics/MethodLength, Metrics/AbcSize

    def show; end

    def new
      @lti_configuration = LtiConfiguration.new(lms_type: nil)
    end

    def info
      lms_type = params[:lms_type]
      @lti_configuration = LtiConfiguration.new(lms_type: lms_type)
    end

    def edit; end

    def update
      if current_lti_configuration.update_attributes(lti_configuration_params)
        flash[:success] = "The configuration was successfully updated."
        redirect_to lti_configuration_path(current_organization)
      else
        flash[:error] = "The configuration could not be updated at this time. Please try again."
        redirect_to edit_lti_configuration_path(current_organization)
      end
    end

    def destroy
      lms_name = current_lti_configuration.lms_name(default_name: "your learning management system")
      GitHubClassroom.statsd.increment("lti_configuration.destroy")
      current_lti_configuration.destroy!
      redirect_to edit_organization_path(current_organization), alert: "Classroom is now disconnected from #{lms_name}."
    end

    def autoconfigure
      not_found unless current_lti_configuration.supports_autoconfiguration?

      xml_configuration = current_lti_configuration.xml_configuration(auth_lti_launch_url)
      render xml: xml_configuration, status: :ok
    end

    def complete; end

    private

    def current_lti_configuration
      @current_lti_configuration ||= current_organization.lti_configuration
    end
    helper_method :current_lti_configuration

    def ensure_current_lti_configuration
      redirect_to info_lti_configuration_path(current_organization) unless current_lti_configuration
    end

    def lti_configuration_params
      params.require(:lti_configuration).permit(:lms_link, :lms_type)
    end

    def ensure_no_google_classroom
      return unless current_organization.google_course_id
      redirect_to edit_organization_path(current_organization),
        alert: "This classroom is already connected to Google Classroom. Please disconnect from Google Classroom "\
          "before connecting to another learning management system."
    end

    def ensure_no_roster
      return unless current_organization.roster
      redirect_to edit_organization_path(current_organization),
        alert: "We are unable to link your classroom organization to a learning management system "\
          "because a roster already exists. Please delete your current roster and try again."
    end

    def ensure_lms_type
      return if params.dig(:lti_configuration, :lms_type).present?
      redirect_to new_lti_configuration_path(current_organization)
    end
  end
end

app/views/orgs/rosters/_download_csv_modal.html.erb
<div class="remodal text-left" data-remodal-id="download-csv-modal">
 <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Select a Grouping</h2>

  <div class="remodal-user-list">
    <%= link_to 'Download without group names', roster_path(format: :csv), class: 'btn btn-primary btn-sm btn-block remodal-button' %>
    <% organization.groupings.map do |grouping| %>
        <%= link_to(
            "Download #{grouping.title}",
            roster_path(grouping: grouping.id, format: :csv),
            class: 'btn btn-sm btn-block remodal-button'
          )
        %>
    <% end %>
  </div>
</div>

app/views/orgs/rosters/_google_classroom_collection.html.erb
<%= form_tag import_from_google_classroom_roster_path, method: :patch do |f| %>
  <div class="Box overflow-scroll">
    <ul>
      <% courses.each_with_index do |course, i| %>
        <li class="Box-row">
          <label>
            <%= radio_button_tag "course_id", course.id, i==0, 'aria-describedby':"help-text-for-checkbox", class:"mr-2" %>
            <%= course.name %>
          </label>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="f4 text-gray text-italic my-3">
    or
    <%= link_to "manually add students",
                new_roster_path,
                class: "btn-link"
    %>
  </div>

  <div class="d-flex flex-items-center border-top pt-5">
    <%= submit_tag 'Import roster', class: 'btn btn-primary mr-3' %>
    <%= link_to 'Skip', organization_path(current_organization), class: 'btn-link' %>
  </div>
<% end %>

app/views/orgs/rosters/_new_student_modal.html.erb
<% view = FormView.new(subject: roster) %>

<div class="remodal text-left" data-remodal-id="new-student-modal">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Add students to your Roster</h2>

    <div class="my-3">
      <h2 class="h4 mb-2">Import students from your institution</h2>
      <% if google_classroom_roster_import_enabled? || lti_launch_enabled? %>
        <p>GitHub Classroom is able to automatically import your roster from your institution. If you
        would rather manage your roster manually, you can still do that, too.</p>

        <%= link_to "Sync from a learning management system",
          link_lms_organization_path,
          class: "btn btn-block btn-sm"
        %>
      <% end %>
    </div>

    <div class="my-3">
      <h2 class="h4 mb-2">Manually add students</h2>
      <div>
        <%= form_tag add_students_roster_path(current_organization), method: :patch do |f| %>
        <div class="Box">
          <dl class="Box-body <%= view.form_class_for(:roster_entries) %> mb-0">
            <dt class="text-gray mb-1">Enter your list of students' identifiers, <strong>one per line</strong>.</dt>
            <dd><%= text_area_tag(:identifiers, '', class: 'form-control input-block', id: 'entries-field', required: true) %></dd>
            <%= render('shared/form_error', errors: view.error_message_for(:roster_entries)) if view.errors_for?(:roster_entries) %>
          </dl>

          <div class="Box-footer bg-gray">
            <label class='btn btn-secondary btn-sm' for="file-upload">Upload a CSV or text file</label>
            <%= file_field_tag :identifiers_file, style: 'display: none', id: 'file-upload', onchange: 'onIdentifiersUploaded()' %>
          </div>
        </div>

          <div class="d-flex flex-items-center border-top pt-5">
            <%= submit_tag 'Add roster entries', class: 'btn btn-primary mr-3' %>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/orgs/rosters/_select_identifier_modal.html.erb
<% view = FormView.new(subject: roster) %>
<% identifiers = local_assigns.fetch(:identifiers, {}) %>
<% lms_name = local_assigns.fetch(:lms_name, "your learning management system") %>

<div class="remodal text-left" data-remodal-id="select-identifier-modal">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Sync Roster from <%= lms_name %></h2>

    <div class="my-3">
      <% if identifiers.present? %>
        <%= form_with url: add_students_roster_path(current_organization), method: :patch do |f| %>
          <div class="Box">
            <dl class="Box-header">
              <h3 class="Box-title">Choose how to identify each imported student</h3>
              <dt class="Box-subtitle">Select from the choices below</dt>
            </dl>
            <ul>
              <%= hidden_field_tag "lms_user_ids", @student_ids %>
              <% identifiers.each_pair do |identifier_type, ids| %>
                <li class="Box-row">
                  <%= f.radio_button :identifiers, ids.join("\r\n") %>&nbsp;
                  <%= f.label :identifiers, identifier_type %>
                </li>
              <% end %>
            </ul>
            <%= render('shared/form_error', errors: view.error_message_for(:roster_entries)) if view.errors_for?(:roster_entries) %>
          </div>
          <div class="d-flex flex-items-center border-top pt-5">
            <%= submit_tag 'Import roster entries', class: 'btn btn-primary mr-3' %>
          </div>
        <% end %>
      <% else %>
        <div class="markdown-body">
          GitHub Classroom received an empty roster from <%= lms_name %>. Please ensure you
          have enabled GitHub Classroom to receive student information per your privacy settings
          from within <%= lms_name %> and try again.
        </div>
        <div class="d-flex flex-items-center pt-3">
          <%= link_to "Cancel", "#", { "data-remodal-action": "close" } %>
        </div>
      <% end %>
    </div>
  </div>

app/views/orgs/rosters/_sync_google_roster_modal.html.erb
<% view = FormView.new(subject: roster) %>
<% course_name = local_assigns.fetch(:course_name, "Google Classroom") %>

<div class="remodal text-left" data-remodal-id="sync-google-roster-modal">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header text-left">Import students from Google Classroom</h2>

  <div class="my-3">
    <div class="f5 mt-2 d-block">Linked to <strong><%= course_name %></strong></div>
    <%= link_to "Sync roster", sync_google_classroom_roster_path, method: :patch, class: "btn btn-sm mt-4" %>
  </div>
</div>

app/views/orgs/rosters/new.html.erb
<% view = FormView.new(subject: @roster) %>

<%= render 'organizations/organization_banner', settings: true %>

<div class="site-content">
  <div class="site-content-cap">
    <h1 class="site-content-heading">Add students</h1>
  </div>
  <div class="site-content-body">
    <div class="markdown-body">
      <p>Let's set up a roster so you can easily track student progress on your dashboard. You can always come back and complete this step later.</p>
    </div>
    <div class="my-3">
      <% if google_classroom_roster_import_enabled? || lti_launch_enabled? %>
        <h2 class="h3 mb-2">Import students from your institution</h2>
        <% if current_organization.lti_configuration %>
          <% lms_name = current_organization.lti_configuration.lms_name(default_name: "your learning management system") %>
          <p>It looks like you are connected to <%= lms_name %>. GitHub Classroom can automatically import your roster for you!</p>

          <%= link_to image_tag('other-logo.png', size: "25", class:"mr-2") + "Import from #{lms_name}",
            import_from_lms_roster_path,
            class: "btn btn-secondary d-inline-flex flex-items-center mb-3"
          %>
        <% elsif current_organization.google_course_id %>
          <p>It looks like you are connected to Google Classroom. GitHub Classroom can automatically import your roster for you!</p>
          <%= link_to image_tag('google-classroom-logo.png', size: "25", class:"mr-2") + "Import from Google Classroom",
            import_from_google_classroom_roster_path(current_organization),
            method: :patch,
            class: "btn btn-secondary d-inline-flex flex-items-center mb-3"
          %>
        <% else %>
          <p>GitHub Classroom is able to automatically import your roster from your institution. If you
          would rather manage your roster manually, you can still do that, too.</p>

          <%= link_to image_tag('other-logo.png', size: "25", class:"mr-2") + "Import from a learning management system",
            link_lms_organization_path,
            class: "btn btn-secondary d-inline-flex flex-items-center mb-3"
          %>
        <% end %>
      <% end %>
    </div>

    <div class="my-3">
      <% if !current_organization.lti_configuration && !current_organization.google_course_id %>
        <h2 class="h3 mb-2">Manually add students</h2>
        <div>
          <%= form_tag roster_path(current_organization), method: :post do |f| %>
            <div class="Box">
              <dl class="Box-body <%= view.form_class_for(:roster_entries) %> mb-0">
                <dt class="text-gray mb-1">Enter your list of students' identifiers, <strong>one per line</strong>.</dt>
                <dd><%= text_area_tag(:identifiers, '', class: 'form-control input-block', id: 'entries-field', required: true) %></dd>
                <%= render('shared/form_error', errors: view.error_message_for(:roster_entries)) if view.errors_for?(:roster_entries) %>
              </dl>

              <div class="Box-footer bg-gray">
                <label class='btn btn-secondary btn-sm' for="file-upload">Upload a CSV or text file</label>
                <%= file_field_tag :identifiers_file, style: 'display: none', id: 'file-upload', onchange: 'onIdentifiersUploaded()' %>
              </div>
            </div>

            <div class="d-flex flex-items-center border-top pt-5">
              <%= submit_tag 'Create roster', class: 'btn btn-primary mr-3' %>
              <%= link_to 'Skip', organization_path(current_organization), class: 'btn-link' %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="d-flex flex-items-center border-top pt-5">
          <%= link_to 'Skip', organization_path(current_organization), class: 'btn-link' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orgs/rosters/show.html.erb
<div class="remodal-bg">
  <%= render 'organizations/organization_banner', settings: true %>

  <div class="columns">
    <div class="one-fourth column">
      <%= render partial: 'organizations/side_menu' %>
    </div>
    <div class="three-fourths column">
      <div class="boxed-group">
        <h3 class='d-flex flex-justify-between flex-items-center'>
          <span>
            Classroom roster
          </span>
          <div class='flex-justify-between'>
            <% if google_classroom_roster_import_enabled? && current_organization.google_course_id %>
              <span class="btn btn-primary btn-sm", role="button" data-remodal-target="sync-google-roster-modal"><%= octicon "sync" %>  Sync from Google Classroom</span>
            <% elsif lti_launch_enabled? && current_organization.lti_configuration %>
              <% lms_name = current_organization.lti_configuration.lms_name(default_name: "learning management system") %>
              <%= link_to import_from_lms_roster_path, remote: true, method: :get, class: "btn btn-primary btn-sm" do %>
                <%= octicon "sync" %>  Sync from <%= lms_name %>
              <% end %>
            <% else %>
              <span class="btn btn-primary btn-sm", role="button" data-remodal-target="new-student-modal">Update students</span>
            <% end %>
            <span class="btn btn-primary btn-sm", role="button" data-remodal-target="download-csv-modal">Download</span>
          </div>
        </h3>

        <div class="site-content-body tabnav-body clearfix">
          <div class="tabnav">
            <nav class="tabnav-tabs">
              <span id='students-tab' onclick="selectTab(this)" class="tabnav-tab selected tabnav-link" aria-current="page">All students</span>
              <span id='unlinked-tab' onclick="selectTab(this)" class="tabnav-tab tabnav-link">Unlinked GitHub accounts</span>
            </nav>
          </div>
          <span id='students-span'>
            <div class="assignment-list-items">
              <% @roster_entries.each do |roster_entry| %>
                <%= render 'roster_entry', roster_entry: roster_entry, roster_entries_page: @roster_entries.current_page %>
              <% end %>

              <div class="d-flex col-12">
                <%= render partial: 'shared/pagination', locals: { collection: @roster_entries, param_name: :roster_entries_page } %>
              </div>
            </div>
          </span>
          <span id='unlinked-span' class='hidden-tab'>
            <div class="assignment-list-items">
              <% if unlinked_users.empty? %>
                <%= render 'shared/unlinked_blank_slate' %>
              <% else %>
                <% @current_unlinked_users.each do |user| %>
                  <%= render 'unlinked_user', unlinked_user: user %>
                <% end %>

                <div class="d-flex col-12">
                  <%= render partial: 'shared/pagination', locals: { collection: @current_unlinked_users, param_name: :unlinked_users_page } %>
                </div>
              <% end %>
            </div>
          </span>
        </div>
      </div>

      <div class="boxed-group dangerzone pb-3">
        <h3>Delete this roster</h3>
        <div class="boxed-group-inner pt-2 clearfix">
          <p>
            Deleting the roster will delete all students.
          </p>
          <p>
            This will not delete assignments, assignment repos, or submissions.
          </p>
            After deleting your roster, repos and submissions will be identified by GitHub handle instead of your roster identifier.
          </p>
          <p>
            <a data-remodal-target="remove-roster" class="btn btn-danger">Delete roster</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'new_student_modal', locals: { roster: current_roster } %>
<%= render partial: 'sync_google_roster_modal', locals: { roster: current_roster, course_name: @google_course_name } %>
<%= render partial: 'download_csv_modal', locals: { roster: current_roster, organization: current_organization } %>
<%= render partial: 'remove_roster_modal', locals: { roster: current_roster, organization: current_organization } %>
<%= render partial: 'select_identifier_modal', locals: { roster: current_roster, organization: current_organization } %>